services:
  db:
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bigtrooper
    ports:
      - 5432:5432
    volumes:
      - ./api/db/init.sql:/docker-entrypoint-initdb.d/init.sql
