// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReport = `-- name: CreateReport :one
INSERT INTO reports (
    pet_id,
    owner_id,
    owner_notified,
    finder_phone,
    finder_email,
    finder_ip,
    finder_latitude,
    finder_longitude
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, pet_id, owner_notified, owner_id, finder_phone, finder_email, finder_ip, finder_latitude, finder_longitude, created_at, updated_at
`

type CreateReportParams struct {
	PetID           int32         `json:"pet_id"`
	OwnerID         int32         `json:"owner_id"`
	OwnerNotified   pgtype.Bool   `json:"owner_notified"`
	FinderPhone     pgtype.Text   `json:"finder_phone"`
	FinderEmail     pgtype.Text   `json:"finder_email"`
	FinderIp        *netip.Addr   `json:"finder_ip"`
	FinderLatitude  pgtype.Float8 `json:"finder_latitude"`
	FinderLongitude pgtype.Float8 `json:"finder_longitude"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.PetID,
		arg.OwnerID,
		arg.OwnerNotified,
		arg.FinderPhone,
		arg.FinderEmail,
		arg.FinderIp,
		arg.FinderLatitude,
		arg.FinderLongitude,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.PetID,
		&i.OwnerNotified,
		&i.OwnerID,
		&i.FinderPhone,
		&i.FinderEmail,
		&i.FinderIp,
		&i.FinderLatitude,
		&i.FinderLongitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteReport = `-- name: DeleteReport :exec
DELETE FROM reports
WHERE id = $1
`

func (q *Queries) DeleteReport(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteReport, id)
	return err
}

const getReportById = `-- name: GetReportById :one
SELECT id, pet_id, owner_notified, owner_id, finder_phone, finder_email, finder_ip, finder_latitude, finder_longitude, created_at, updated_at
FROM reports
WHERE id = $1
`

func (q *Queries) GetReportById(ctx context.Context, id int32) (Report, error) {
	row := q.db.QueryRow(ctx, getReportById, id)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.PetID,
		&i.OwnerNotified,
		&i.OwnerID,
		&i.FinderPhone,
		&i.FinderEmail,
		&i.FinderIp,
		&i.FinderLatitude,
		&i.FinderLongitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReports = `-- name: ListReports :many
SELECT id, pet_id, owner_notified, owner_id, finder_phone, finder_email, finder_ip, finder_latitude, finder_longitude, created_at, updated_at
FROM reports
ORDER BY created_at DESC
`

func (q *Queries) ListReports(ctx context.Context) ([]Report, error) {
	rows, err := q.db.Query(ctx, listReports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.PetID,
			&i.OwnerNotified,
			&i.OwnerID,
			&i.FinderPhone,
			&i.FinderEmail,
			&i.FinderIp,
			&i.FinderLatitude,
			&i.FinderLongitude,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReportNotified = `-- name: MarkReportNotified :exec
UPDATE reports
SET owner_notified = TRUE,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) MarkReportNotified(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, markReportNotified, id)
	return err
}

const updateReport = `-- name: UpdateReport :exec
UPDATE reports
SET pet_id = $1,
    owner_id = $2,
    owner_notified = $3,
    finder_phone = $4,
    finder_email = $5,
    finder_ip = $6,
    finder_latitude = $7,
    finder_longitude = $8,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $9
`

type UpdateReportParams struct {
	PetID           int32         `json:"pet_id"`
	OwnerID         int32         `json:"owner_id"`
	OwnerNotified   pgtype.Bool   `json:"owner_notified"`
	FinderPhone     pgtype.Text   `json:"finder_phone"`
	FinderEmail     pgtype.Text   `json:"finder_email"`
	FinderIp        *netip.Addr   `json:"finder_ip"`
	FinderLatitude  pgtype.Float8 `json:"finder_latitude"`
	FinderLongitude pgtype.Float8 `json:"finder_longitude"`
	ID              int32         `json:"id"`
}

func (q *Queries) UpdateReport(ctx context.Context, arg UpdateReportParams) error {
	_, err := q.db.Exec(ctx, updateReport,
		arg.PetID,
		arg.OwnerID,
		arg.OwnerNotified,
		arg.FinderPhone,
		arg.FinderEmail,
		arg.FinderIp,
		arg.FinderLatitude,
		arg.FinderLongitude,
		arg.ID,
	)
	return err
}
