// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: articles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles (slug, title, date, category_id, published, deleted, body, excerpt, created_at, updated_at) 
VALUES ($1, $2, $3, $4, $5, FALSE, $6, $7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) RETURNING id, slug, title, date, category_id, published, deleted, excerpt, body, created_at, updated_at
`

type CreateArticleParams struct {
	Slug       string      `json:"slug"`
	Title      string      `json:"title"`
	Date       pgtype.Date `json:"date"`
	CategoryID int32       `json:"category_id"`
	Published  bool        `json:"published"`
	Body       string      `json:"body"`
	Excerpt    string      `json:"excerpt"`
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error) {
	row := q.db.QueryRow(ctx, createArticle,
		arg.Slug,
		arg.Title,
		arg.Date,
		arg.CategoryID,
		arg.Published,
		arg.Body,
		arg.Excerpt,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Date,
		&i.CategoryID,
		&i.Published,
		&i.Deleted,
		&i.Excerpt,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteArticle = `-- name: DeleteArticle :exec
UPDATE articles SET deleted = TRUE WHERE id = $1
`

func (q *Queries) DeleteArticle(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteArticle, id)
	return err
}

const getArticleById = `-- name: GetArticleById :one
SELECT a.id, a.slug, a.title, a.date, a.category_id, a.published, a.deleted, a.excerpt, a.body, a.created_at, a.updated_at, c.id, c.name, c.description, c.created_at, c.updated_at
FROM articles a
JOIN categories c ON c.id = a.category_id
WHERE a.deleted = FALSE AND a.id = $1
ORDER BY a.date DESC
`

type GetArticleByIdRow struct {
	ID         int32              `json:"id"`
	Slug       string             `json:"slug"`
	Title      string             `json:"title"`
	Date       pgtype.Date        `json:"date"`
	CategoryID int32              `json:"category_id"`
	Published  bool               `json:"published"`
	Deleted    bool               `json:"deleted"`
	Excerpt    string             `json:"excerpt"`
	Body       string             `json:"body"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	Category   Category           `json:"category"`
}

func (q *Queries) GetArticleById(ctx context.Context, id int32) (GetArticleByIdRow, error) {
	row := q.db.QueryRow(ctx, getArticleById, id)
	var i GetArticleByIdRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Date,
		&i.CategoryID,
		&i.Published,
		&i.Deleted,
		&i.Excerpt,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category.ID,
		&i.Category.Name,
		&i.Category.Description,
		&i.Category.CreatedAt,
		&i.Category.UpdatedAt,
	)
	return i, err
}

const getArticleBySlug = `-- name: GetArticleBySlug :one

SELECT a.id, a.slug, a.title, a.date, a.category_id, a.published, a.deleted, a.excerpt, a.body, a.created_at, a.updated_at, c.id, c.name, c.description, c.created_at, c.updated_at
FROM articles a
JOIN categories c ON c.id = a.category_id
WHERE a.deleted = FALSE AND a.slug = $1
ORDER BY a.date DESC
`

type GetArticleBySlugRow struct {
	ID         int32              `json:"id"`
	Slug       string             `json:"slug"`
	Title      string             `json:"title"`
	Date       pgtype.Date        `json:"date"`
	CategoryID int32              `json:"category_id"`
	Published  bool               `json:"published"`
	Deleted    bool               `json:"deleted"`
	Excerpt    string             `json:"excerpt"`
	Body       string             `json:"body"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	Category   Category           `json:"category"`
}

func (q *Queries) GetArticleBySlug(ctx context.Context, slug string) (GetArticleBySlugRow, error) {
	row := q.db.QueryRow(ctx, getArticleBySlug, slug)
	var i GetArticleBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Date,
		&i.CategoryID,
		&i.Published,
		&i.Deleted,
		&i.Excerpt,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category.ID,
		&i.Category.Name,
		&i.Category.Description,
		&i.Category.CreatedAt,
		&i.Category.UpdatedAt,
	)
	return i, err
}

const getArticleCount = `-- name: GetArticleCount :one
SELECT COUNT(*) FROM articles WHERE deleted = FALSE
`

func (q *Queries) GetArticleCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getArticleCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listAllArticles = `-- name: ListAllArticles :many
SELECT a.id, a.title, a.excerpt, a.slug, a.date, a.published, c.id, c.name, c.description, c.created_at, c.updated_at
FROM articles a
JOIN categories c ON c.id = a.category_id
WHERE a.deleted = FALSE
ORDER BY a.date DESC
`

type ListAllArticlesRow struct {
	ID        int32       `json:"id"`
	Title     string      `json:"title"`
	Excerpt   string      `json:"excerpt"`
	Slug      string      `json:"slug"`
	Date      pgtype.Date `json:"date"`
	Published bool        `json:"published"`
	Category  Category    `json:"category"`
}

func (q *Queries) ListAllArticles(ctx context.Context) ([]ListAllArticlesRow, error) {
	rows, err := q.db.Query(ctx, listAllArticles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllArticlesRow
	for rows.Next() {
		var i ListAllArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Excerpt,
			&i.Slug,
			&i.Date,
			&i.Published,
			&i.Category.ID,
			&i.Category.Name,
			&i.Category.Description,
			&i.Category.CreatedAt,
			&i.Category.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedArticles = `-- name: ListPublishedArticles :many
SELECT a.id, a.title, a.excerpt, a.slug, a.date, a.published, c.id, c.name, c.description, c.created_at, c.updated_at
FROM articles a
JOIN categories c ON c.id = a.category_id
WHERE a.deleted = FALSE AND a.published = TRUE
ORDER BY a.date DESC
`

type ListPublishedArticlesRow struct {
	ID        int32       `json:"id"`
	Title     string      `json:"title"`
	Excerpt   string      `json:"excerpt"`
	Slug      string      `json:"slug"`
	Date      pgtype.Date `json:"date"`
	Published bool        `json:"published"`
	Category  Category    `json:"category"`
}

func (q *Queries) ListPublishedArticles(ctx context.Context) ([]ListPublishedArticlesRow, error) {
	rows, err := q.db.Query(ctx, listPublishedArticles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedArticlesRow
	for rows.Next() {
		var i ListPublishedArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Excerpt,
			&i.Slug,
			&i.Date,
			&i.Published,
			&i.Category.ID,
			&i.Category.Name,
			&i.Category.Description,
			&i.Category.CreatedAt,
			&i.Category.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArticle = `-- name: UpdateArticle :exec
UPDATE articles SET slug = $1, title = $2, date = $3, category_id = $4, published = $5, body = $6, excerpt = $7, updated_at = CURRENT_TIMESTAMP WHERE id = $8
`

type UpdateArticleParams struct {
	Slug       string      `json:"slug"`
	Title      string      `json:"title"`
	Date       pgtype.Date `json:"date"`
	CategoryID int32       `json:"category_id"`
	Published  bool        `json:"published"`
	Body       string      `json:"body"`
	Excerpt    string      `json:"excerpt"`
	ID         int32       `json:"id"`
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) error {
	_, err := q.db.Exec(ctx, updateArticle,
		arg.Slug,
		arg.Title,
		arg.Date,
		arg.CategoryID,
		arg.Published,
		arg.Body,
		arg.Excerpt,
		arg.ID,
	)
	return err
}
