// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: articles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles (slug, title, date, category_id, published, deleted, body, excerpt, created_at, updated_at) 
VALUES ($1, $2, $3, $4, $5, FALSE, $6, $7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) RETURNING id, slug, title, date, category_id, published, deleted, excerpt, body, created_at, updated_at
`

type CreateArticleParams struct {
	Slug       string      `json:"slug"`
	Title      string      `json:"title"`
	Date       pgtype.Date `json:"date"`
	CategoryID int32       `json:"category_id"`
	Published  bool        `json:"published"`
	Body       string      `json:"body"`
	Excerpt    string      `json:"excerpt"`
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error) {
	row := q.db.QueryRow(ctx, createArticle,
		arg.Slug,
		arg.Title,
		arg.Date,
		arg.CategoryID,
		arg.Published,
		arg.Body,
		arg.Excerpt,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Date,
		&i.CategoryID,
		&i.Published,
		&i.Deleted,
		&i.Excerpt,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteArticle = `-- name: DeleteArticle :exec
UPDATE articles SET deleted = TRUE WHERE id = $1
`

func (q *Queries) DeleteArticle(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteArticle, id)
	return err
}

const getArticle = `-- name: GetArticle :one
SELECT id, slug, title, date, category_id, published, deleted, excerpt, body, created_at, updated_at FROM articles WHERE id = $1 AND deleted = FALSE
`

func (q *Queries) GetArticle(ctx context.Context, id int32) (Article, error) {
	row := q.db.QueryRow(ctx, getArticle, id)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Date,
		&i.CategoryID,
		&i.Published,
		&i.Deleted,
		&i.Excerpt,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArticleCount = `-- name: GetArticleCount :one
SELECT COUNT(*) FROM articles WHERE deleted = FALSE
`

func (q *Queries) GetArticleCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getArticleCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listArticles = `-- name: ListArticles :many
SELECT id, title, excerpt, category_id, slug, date FROM articles WHERE deleted = FALSE
`

type ListArticlesRow struct {
	ID         int32       `json:"id"`
	Title      string      `json:"title"`
	Excerpt    string      `json:"excerpt"`
	CategoryID int32       `json:"category_id"`
	Slug       string      `json:"slug"`
	Date       pgtype.Date `json:"date"`
}

func (q *Queries) ListArticles(ctx context.Context) ([]ListArticlesRow, error) {
	rows, err := q.db.Query(ctx, listArticles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArticlesRow
	for rows.Next() {
		var i ListArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Excerpt,
			&i.CategoryID,
			&i.Slug,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArticle = `-- name: UpdateArticle :exec
UPDATE articles SET slug = $1, title = $2, date = $3, category_id = $4, published = $5, body = $6, excerpt = $7, updated_at = CURRENT_TIMESTAMP WHERE id = $8
`

type UpdateArticleParams struct {
	Slug       string      `json:"slug"`
	Title      string      `json:"title"`
	Date       pgtype.Date `json:"date"`
	CategoryID int32       `json:"category_id"`
	Published  bool        `json:"published"`
	Body       string      `json:"body"`
	Excerpt    string      `json:"excerpt"`
	ID         int32       `json:"id"`
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) error {
	_, err := q.db.Exec(ctx, updateArticle,
		arg.Slug,
		arg.Title,
		arg.Date,
		arg.CategoryID,
		arg.Published,
		arg.Body,
		arg.Excerpt,
		arg.ID,
	)
	return err
}
