// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Article struct {
	ID         int32              `json:"id"`
	Slug       string             `json:"slug"`
	Title      string             `json:"title"`
	Date       pgtype.Date        `json:"date"`
	CategoryID int32              `json:"category_id"`
	Published  bool               `json:"published"`
	Deleted    bool               `json:"deleted"`
	Excerpt    string             `json:"excerpt"`
	Body       string             `json:"body"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Category struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Pet struct {
	ID          int32              `json:"id"`
	OwnerID     int32              `json:"owner_id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	Type        string             `json:"type"`
	Age         int32              `json:"age"`
	Description string             `json:"description"`
	Active      bool               `json:"active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ImageKey    pgtype.Text        `json:"image_key"`
}

type Session struct {
	ID        int32              `json:"id"`
	UserID    int32              `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID          int32              `json:"id"`
	FirstName   string             `json:"first_name"`
	LastName    string             `json:"last_name"`
	Email       string             `json:"email"`
	PhoneNumber string             `json:"phone_number"`
	Password    string             `json:"password"`
	Preferences []byte             `json:"preferences"`
	Admin       bool               `json:"admin"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
