// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Pet struct {
	ID          int32              `json:"id"`
	OwnerID     int32              `json:"owner_id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	Type        string             `json:"type"`
	Age         int32              `json:"age"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID          int32              `json:"id"`
	FirstName   string             `json:"first_name"`
	LastName    string             `json:"last_name"`
	Email       string             `json:"email"`
	PhoneNumber string             `json:"phone_number"`
	Password    string             `json:"password"`
	Preferences []byte             `json:"preferences"`
	Admin       bool               `json:"admin"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
