// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pets.sql

package db

import (
	"context"
)

const createPet = `-- name: CreatePet :one
INSERT INTO pets (owner_id, code, name, type, age, description) 
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, owner_id, code, name, type, age, description, created_at, updated_at
`

type CreatePetParams struct {
	OwnerID     int32  `json:"owner_id"`
	Code        string `json:"code"`
	Name        string `json:"name"`
	Type        string `json:"type"`
	Age         int32  `json:"age"`
	Description string `json:"description"`
}

func (q *Queries) CreatePet(ctx context.Context, arg CreatePetParams) (Pet, error) {
	row := q.db.QueryRow(ctx, createPet,
		arg.OwnerID,
		arg.Code,
		arg.Name,
		arg.Type,
		arg.Age,
		arg.Description,
	)
	var i Pet
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.Age,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePet = `-- name: DeletePet :exec
DELETE FROM pets WHERE id = $1
`

func (q *Queries) DeletePet(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePet, id)
	return err
}

const getPetByCode = `-- name: GetPetByCode :one
SELECT id, owner_id, code, name, type, age, description, created_at, updated_at FROM pets WHERE code = $1
`

func (q *Queries) GetPetByCode(ctx context.Context, code string) (Pet, error) {
	row := q.db.QueryRow(ctx, getPetByCode, code)
	var i Pet
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.Age,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPetById = `-- name: GetPetById :one
SELECT id, owner_id, code, name, type, age, description, created_at, updated_at FROM pets WHERE id = $1
`

func (q *Queries) GetPetById(ctx context.Context, id int32) (Pet, error) {
	row := q.db.QueryRow(ctx, getPetById, id)
	var i Pet
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.Age,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePet = `-- name: UpdatePet :exec
UPDATE pets SET owner_id = $1, code = $2, name = $3, type = $4, age = $5, description = $6, updated_at = CURRENT_TIMESTAMP WHERE id = $7
`

type UpdatePetParams struct {
	OwnerID     int32  `json:"owner_id"`
	Code        string `json:"code"`
	Name        string `json:"name"`
	Type        string `json:"type"`
	Age         int32  `json:"age"`
	Description string `json:"description"`
	ID          int32  `json:"id"`
}

func (q *Queries) UpdatePet(ctx context.Context, arg UpdatePetParams) error {
	_, err := q.db.Exec(ctx, updatePet,
		arg.OwnerID,
		arg.Code,
		arg.Name,
		arg.Type,
		arg.Age,
		arg.Description,
		arg.ID,
	)
	return err
}
